name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Debug
        run: |
         echo "USER: ${{ secrets.EC2_NAME }}"
         echo "HOST: ${{ secrets.EC2_HOST }}"
